CREATE SCHEMA ironhack_homework3;
USE ironhack_homework3;

CREATE TABLE `accounts` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `INDUSTRY` varchar(40) DEFAULT NULL,
  `EMPLOYEE_COUNT` int DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `COUNTRY` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `contacts` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) DEFAULT NULL,
  `PHONE_NUMBER` INT,
  `EMAIL` varchar(100) DEFAULT NULL,
  `COMPANY_NAME` varchar(40) DEFAULT NULL,
  `ACCOUNT_ID` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ACCOUNT_ID` (`ACCOUNT_ID`),
  FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `accounts` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;




CREATE TABLE `sales_rep` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `opportunities` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PRODUCT` varchar(40) DEFAULT NULL,
  `STATUS` varchar(40) DEFAULT NULL,
  `QUANTITY` INT DEFAULT NULL,
  `SALES_REP_ID` int DEFAULT NULL,
  `ACCOUNT_ID` int DEFAULT NULL,
  `DECISION_MAKER` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SALES_REP_ID` (`SALES_REP_ID`),
  KEY `ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `fk_opportunities_contacts1_idx` (`DECISION_MAKER`),
  FOREIGN KEY (`DECISION_MAKER`) REFERENCES `contacts` (`ID`),
  FOREIGN KEY (`SALES_REP_ID`) REFERENCES `sales_rep` (`ID`),
  FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `accounts` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `leads` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `LEAD_NAME` varchar(40) DEFAULT NULL,
  `PHONE_NUMBER` INT,
  `EMAIL` varchar(100) DEFAULT NULL,
  `COMPANY_NAME` varchar(40) DEFAULT NULL,
  `SALES_REP_ID` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_leads_sales_rep1_idx` (`SALES_REP_ID`),
  FOREIGN KEY (`SALES_REP_ID`) REFERENCES `sales_rep` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
